import type{Metadata}from"next";
import {ContextualHero,ContextualOutcomes}from"@/components/contextual-home";
import {SiteShell}from"@/components/site-shell";
import {ButtonLink}from"@/components/ui/button-link";
import {ProblemSelector}from"@/components/problem-selector";
import {ProcessFlow}from"@/components/process-flow";
import {SectionHeading}from"@/components/sections/section-heading";
import {SystemDiagram}from"@/components/visuals/system-diagram";
export const metadata:Metadata={alternates:{canonical:"/"}};
const signals=["Leads waiting too long for follow-up","Tasks depending on someone remembering","No clear owner when something goes wrong","Information spread across disconnected tools","Repetitive coordination consuming staff time","Poor visibility into what is actually happening","Inconsistent processes between employees","Too much knowledge trapped in one person"];
export default function Home(){return <SiteShell><ContextualHero/>
<section className="section-rule bg-white py-18 sm:py-28"><div className="mx-auto max-w-[var(--page-width)] px-5 lg:px-8"><SectionHeading eyebrow="Operational signals" title="The friction is often visible before the system is.">These are signals to notice, not assumptions to make. A diagnostic brings them into focus before they become the way work has to happen.</SectionHeading><div className="mt-12 grid gap-x-10 md:grid-cols-2">{signals.map((signal,index)=><div className="group flex gap-4 border-t border-[var(--line)] py-5" key={signal}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-[var(--line)] font-mono text-[10px] text-[var(--brand)] transition group-hover:border-[var(--brand)] group-hover:bg-[var(--brand-wash)]">0{index+1}</span><p className="font-semibold leading-7">{signal}</p><span className="ml-auto mt-2 h-2 w-2 shrink-0 rounded-full bg-[var(--line-strong)] group-hover:bg-[var(--brand)]"/></div>)}</div></div></section>
<ProblemSelector/>
<section className="section-rule py-18 sm:py-28"><div className="mx-auto max-w-[var(--page-width)] px-5 lg:px-8"><SectionHeading eyebrow="Technology follows diagnosis" title="A tool can add activity. A system makes work dependable.">The point is not to reject software. It is to understand the operation first, so the technology has a clear job to do.</SectionHeading><div className="mt-12 grid gap-5 lg:grid-cols-2"><article className="rounded-[var(--radius-card)] border border-[var(--line)] bg-white p-7"><p className="eyebrow text-[var(--ink-muted)]">Tool-first</p><h3 className="mt-4 text-2xl font-semibold tracking-[-.04em]">Buy first. Then force the work to fit.</h3><ol className="mt-8 space-y-3 text-[var(--ink-muted)]">{["A problem appears","A tool is selected","The process bends around it","Another dependency is created"].map((item,i)=><li className="flex gap-3" key={item}><span className="font-mono text-xs">0{i+1}</span>{item}</li>)}</ol></article><article className="rounded-[var(--radius-card)] bg-[var(--brand-deep)] p-7 text-white"><p className="eyebrow text-[var(--accent)]">System-first</p><h3 className="mt-4 text-2xl font-semibold tracking-[-.04em]">Understand first. Then make the flow work.</h3><ol className="mt-8 space-y-3 text-white/75">{["Understand the operation","Identify the failure point","Design the required flow","Select or build the supporting technology","Validate the outcome"].map((item,i)=><li className="flex gap-3" key={item}><span className="font-mono text-xs text-[var(--accent)]">0{i+1}</span>{item}</li>)}</ol></article></div></div></section>
<section className="section-rule bg-[var(--brand-deep)] py-18 text-white sm:py-28"><div className="mx-auto max-w-[var(--page-width)] px-5 lg:px-8"><SectionHeading eyebrow="How it works" title="A connected path from uncertainty to control."><span className="text-white/70">The work is rigorous behind the scenes and clear for the people accountable for the result.</span></SectionHeading><div className="mt-12"><ProcessFlow dark/></div></div></section>
<ContextualOutcomes/>
<section className="section-rule bg-[var(--surface-muted)] py-18 sm:py-28"><div className="mx-auto grid max-w-[var(--page-width)] gap-10 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><SectionHeading eyebrow="A controlled delivery layer" title="The work stays clear as it moves.">Avuhz is Sekinfra&apos;s operating infrastructure for keeping diagnostics, scope, authority, implementation, and change controlled.</SectionHeading><p className="mt-6 text-sm text-[var(--ink-muted)]">For you, that means clearer decisions, fewer surprises, and accountable implementation.</p></div><SystemDiagram variant="control"/><div className="lg:col-span-2 grid gap-3 sm:grid-cols-3">{["Clear decisions","Controlled scope","Traceable change","Less confusion","Fewer surprises","Accountable implementation"].map(item=><div className="rounded-lg border border-[var(--line)] bg-white px-4 py-4 font-semibold" key={item}>{item}</div>)}</div></div></section>
<section className="py-22 sm:py-30"><div className="mx-auto max-w-3xl px-5 text-center"><p className="eyebrow">Begin with what is true</p><h2 className="text-balance mt-5 text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Understand what is happening before prescribing what to build.</h2><p className="mx-auto mt-6 max-w-2xl text-lg text-[var(--ink-muted)]">A diagnostic is the first practical step toward an operation that is easier to run and easier to trust.</p><ButtonLink href="/start" className="mt-8">Start a Diagnostic</ButtonLink></div></section></SiteShell>}
