"""Safe runtime reason values; these mirror existing Slice 1 contract reason codes."""

from enum import StrEnum


class RuntimeReason(StrEnum):
    SCHEMA_UNSUPPORTED = "SCHEMA_UNSUPPORTED"
    PAYLOAD_INVALID = "PAYLOAD_INVALID"
    FIELD_FORBIDDEN = "FIELD_FORBIDDEN"
    VERSION_REQUIRED = "VERSION_REQUIRED"
    AUTH_MISSING = "AUTH_MISSING"
    AUTH_INVALID = "AUTH_INVALID"
    AUTH_EXPIRED = "AUTH_EXPIRED"
    AUTH_AUDIENCE_INVALID = "AUTH_AUDIENCE_INVALID"
    AUTH_CAPABILITY_MISSING = "AUTH_CAPABILITY_MISSING"
    TENANT_CONTEXT_MISSING = "TENANT_CONTEXT_MISSING"
    TENANT_ACCESS_DENIED = "TENANT_ACCESS_DENIED"
    TENANT_SUBJECT_MISMATCH = "TENANT_SUBJECT_MISMATCH"
    CROSS_TENANT_ATTEMPT = "CROSS_TENANT_ATTEMPT"
    VERSION_STALE = "VERSION_STALE"
    INTERNAL_INVARIANT_VIOLATION = "INTERNAL_INVARIANT_VIOLATION"
