"""Provider-neutral Slice 1 persistence ports; no generic CRUD or database concepts."""
from typing import Protocol
class AcquisitionHandoffRepository(Protocol):
 def get(self,tenant_id:str,handoff_id:str):...
 def save_accepted(self,record:dict):...
class EngagementRepository(Protocol):
 def get(self,tenant_id:str,engagement_id:str):...
 def exists(self,tenant_id:str,engagement_id:str)->bool:...
 def save(self,record:dict):...
class DiagnosticScopeRepository(Protocol):
 def get(self,tenant_id:str,scope_id:str):...
 def save(self,record:dict):...
 def set_canonical_scope_digest(self,tenant_id:str,scope_id:str,scope_version:int,expected_record_version:int,digest:str):...
class DiagnosticAgreementAuthorityRepository(Protocol):
 def get(self,tenant_id:str,diagnostic_agreement_authority_id:str):...
 def create(self,record:dict):...
class DiagnosticPaymentVerificationRepository(Protocol):
 def get(self,tenant_id:str,diagnostic_payment_verification_id:str):...
 def create(self,record:dict):...
 def invalidate(self,tenant_id:str,diagnostic_payment_verification_id:str,invalidated_at:str):...

class AssessmentAccessProposalRepository(Protocol):
 def get(self,tenant_id:str,assessment_access_proposal_id:str):...
 def create(self,proposal:dict):...

 def consume(self,tenant_id:str,assessment_access_proposal_id:str,digest:str,consumed_at:str):...

class AssessmentAccessGrantRepository(Protocol):
 def get(self,tenant_id:str,assessment_access_grant_id:str):...
 def create(self,grant:dict):...
 def activate(self,tenant_id:str,assessment_access_grant_id:str,digest:str,verified_at:str,expires_at:str):...
 def expire(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def revoke(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def close_for_agreement_end(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def close_for_lifecycle(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str,closure_reason:str):...
 def expire(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def revoke(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
 def close_for_agreement_end(self,tenant_id:str,assessment_access_grant_id:str,trusted_now:str):...
class AssessmentAccessVerifier(Protocol):
 def verify(self,request):...

class OIAAssessmentRepository(Protocol):
 def get(self,tenant_id:str,oia_assessment_id:str):...
 def find_by_assessment_access_grant(self,tenant_id:str,assessment_access_grant_id:str):...
 def create(self,assessment:dict):...
 def mark_ready(self,current:dict,ready_at:str):...
 def mark_delivered(self,current:dict,delivery:dict,delivered_at:str):...
 def reopen_for_correction(self,current:dict,reopened_at:str):...
 def close(self,current:dict,closed_at:str):...
 def status_view(self,tenant_id:str,oia_assessment_id:str,generated_at:str):...

class OIAEvidenceRepository(Protocol):
 def get(self,tenant_id:str,oia_evidence_id:str):...
 def create(self,evidence:dict):...

class OIAAssessmentPlanRepository(Protocol):
 def get_version(self,tenant_id:str,oia_assessment_plan_id:str,plan_version:int):...
 def get_current(self,tenant_id:str,oia_assessment_plan_id:str):...
 def find_current_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def list_versions(self,tenant_id:str,oia_assessment_plan_id:str):...
 def create_initial(self,plan:dict):...
 def revise(self,current:dict,replacement:dict,revised_at:str):...
 def review(self,current:dict,reviewed_by:str,reviewed_at:str):...
 def approve(self,current:dict,approved_by:str,approved_at:str):...

class OIAInspectionItemRepository(Protocol):
 def get(self,tenant_id:str,oia_inspection_item_id:str):...
 def list_by_plan(self,tenant_id:str,oia_assessment_plan_id:str,plan_version:int):...
 def list_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def create(self,item:dict):...
 def update(self,current:dict,payload:dict,updated_by:str,updated_at:str):...
 def block(self,current:dict,payload:dict,updated_by:str,updated_at:str,stop_reason:str|None):...
 def coverage_for_plan(self,tenant_id:str,oia_assessment_plan_id:str,plan_version:int):...
 def coverage_for_current_assessment(self,tenant_id:str,oia_assessment_id:str):...

class OIAObservationRepository(Protocol):
 def get(self,tenant_id:str,oia_observation_id:str):...
 def list_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def list_current_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def resolve_current(self,tenant_id:str,oia_observation_id:str):...
 def create(self,observation:dict):...
 def supersede(self,original:dict,replacement:dict,superseded_at:str):...

class OIARootCauseRepository(Protocol):
 def get(self,tenant_id:str,oia_root_cause_id:str):...
 def list_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def create(self,root_cause:dict):...
 def transition(self,current:dict,payload:dict,updated_at:str):...

class OIAFindingRepository(Protocol):
 def get(self,tenant_id:str,oia_finding_id:str):...
 def get_revision(self,tenant_id:str,oia_finding_id:str,finding_revision:int):...
 def list_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def list_current_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def create(self,finding:dict):...
 def revise(self,current:dict,replacement:dict,content_digest:str,updated_at:str):...
 def finalize(self,current:dict,final:dict):...
 def open_delivered_correction(self,original:dict,replacement:dict,opened_at:str):...
 def summary_by_assessment(self,tenant_id:str,oia_assessment_id:str,generated_at:str):...

class OIAFindingsDeliveryRepository(Protocol):
 def get(self,tenant_id:str,oia_findings_delivery_id:str):...
 def list_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def latest_by_assessment(self,tenant_id:str,oia_assessment_id:str):...
 def create(self,delivery:dict):...
 def status_view(self,tenant_id:str,oia_assessment_id:str,assessment_state:str,generated_at:str):...

class OIAConversionDecisionRepository(Protocol):
 def get_version(self,tenant_id:str,decision_id:str,decision_version:int):...
 def get_current(self,tenant_id:str,decision_id:str):...
 def find_current_by_engagement(self,tenant_id:str,engagement_id:str):...
 def create(self,record:dict):...
 def accept(self,current:dict,sekinfra_approval_reference:dict,accepted_at:str):...

class OngoingAgreementAuthorityRepository(Protocol):
 def get_version(self,tenant_id:str,agreement_id:str,agreement_version:int):...
 def get_current(self,tenant_id:str,agreement_id:str):...
 def find_current_by_engagement(self,tenant_id:str,engagement_id:str):...
 def create(self,record:dict):...
 def activate(self,current:dict,client_approval_reference:dict,sekinfra_approval_reference:dict,activated_at:str):...
 def terminate(self,current:dict,state:str,reason:str,terminal_at:str):...

class OngoingPaymentVerificationRepository(Protocol):
 def get(self,tenant_id:str,payment_id:str):...
 def find_current_by_engagement(self,tenant_id:str,engagement_id:str):...
 def create(self,record:dict):...
 def invalidate(self,current:dict,reason:str,invalidated_at:str):...

class OngoingAccessGrantRepository(Protocol):
 def get(self,tenant_id:str,grant_id:str):...
 def find_current_by_engagement(self,tenant_id:str,engagement_id:str):...
 def create(self,record:dict):...
 def approve(self,current:dict,client_approval_reference:dict,sekinfra_approval_reference:dict,approved_at:str):...
 def activate(self,current:dict,verified_at:str):...
 def revoke(self,current:dict,reason:str,revoked_at:str):...
 def close(self,current:dict,reason:str,closed_at:str):...

class OngoingAccessRevocationVerificationRepository(Protocol):
 def get(self,tenant_id:str,verification_id:str):...
 def list_by_grant(self,tenant_id:str,grant_id:str,offboarding_id:str|None=None):...
 def list_by_offboarding(self,tenant_id:str,offboarding_id:str):...
 def create(self,record:dict):...

class OngoingOffboardingRepository(Protocol):
 def get(self,tenant_id:str,offboarding_id:str):...
 def find_by_engagement(self,tenant_id:str,engagement_id:str):...
 def create(self,record:dict):...
 def complete(self,current:dict,verification_references:list,completed_at:str,completed_by:str):...

class HumanApprovalRepository(Protocol):
 def get(self,tenant_id:str,approval_id:str):...
 def record_assessment_access(self,record:dict):...
 def find_active_assessment_access_binding(self,tenant_id:str,proposal_id:str,digest:str,authority_role:str):...
 def list_active_assessment_access_bindings(self,tenant_id:str,proposal_id:str,digest:str,authority_role:str):...
 def save(self,record:dict):...
 def find_active_binding(self,tenant_id:str,scope_id:str,scope_version:int,authority_role:str,digest:str,action_set_version:int):...
 def record_phase5c(self,record:dict):...
 def find_active_phase5c_binding(self,tenant_id:str,subject_type:str,subject_id:str,subject_version:int,digest:str,authority_role:str):...
class IdempotencyRepository(Protocol):
 def get(self,key:tuple):...
 def save_result(self,key:tuple,result:dict):...
class LifecycleEventRepository(Protocol):
 def append(self,event:dict):...
class OutboxRepository(Protocol):
 def append(self,intent:dict):...
class UnitOfWorkPort(Protocol):
 def commit(self):...
